name: ZAP Scan
on:
  push:
    branches:
      - feat/integrate-zap-2
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ./zap/zap_scan.sh

      - name: Run ZAP Scan
        run: ./zap/zap_scan.sh
